apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wazuh
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/wazuh
  prune: true
  sourceRef:
    kind: GitRepository
    name: your-repo-name
    namespace: flux-system
  targetNamespace: wazuh
  dependsOn:
    - name: longhorn
    - name: cert-manager