apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wazuh
  namespace: wazuh
spec:
  interval: 5m
  chart:
    spec:
      chart: wazuh
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: wazuh-helm
        namespace: flux-system
  values:
    manager:
      enabled: true
      service:
        type: ClusterIP
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
    indexer:
      enabled: true
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "4"
          memory: "8Gi"
      volumeClaimTemplate:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
        storageClassName: longhorn
    dashboard:
      enabled: true
      service:
        type: LoadBalancer
      auth:
        password: "${WAZUH_DASHBOARD_PASSWORD}"
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "4"
          memory: "8Gi"
    filebeat:
      enabled: true